openapi: 3.0.3
info:
  title: Partena Mediation Layer - Worker API
  version: 0.10.0
  description: |
    <h1>DRAFT - to be reviewed</h1>
    <h2>To Do for v1.0.0:</h2><br>
    <p>[/] => in-progress</p>
    <p>[-] => to do</p>
    <p>[X] => done</p>
    <ul>
      <li>[X] More elaborate general descriptions for operations, including guidelines in terms of required request attributes for specific scenarios.</li>
      <li>[X] More elaborate descriptions per response type, including guidelines for suggested error handling.</li>
      <li>[X] Provide example of descriptive <i>errorReason</i> that provide remediation guidance.</li>
      <li>[X] Finalize request and response schemas.</li>
      <li>[X] Define AuthN / authZ. <i>(TBD by Minggo)</i></li>
      <li>[/] Validate solution through first E2E UAT</i></li>
    </ul>

paths:
  /wd-es/v1/worker/:
    post:
      summary: Create worker (New Hire)
      tags: [New Hire]
      description: |
        Upon onboarding a new Hire in your HRIS, this interface should be used to register that same Worker on Partena's side.<br><br>
        <u><b>Baseline principles:</b></u><br>
        <ul>
          <li><b>Required request body attributes:</b> all request schema attributes are required to enable payrolling, but not necessarily required to register a Worker in ExpertSalary. Attributes that are not marked as <i>required *</i> in the request schema below can later be provided through the Change-operation in order to render the Worker payrolling-eligable.<br><br>
          <ul>
            <li><b>Exceptions:</b>
              <ul>
                <li>The <b><i>relatedPersons</i>-array</b> should only be populated for the Hire's partnerships that are relevant for Belgian payrolling (children, spouse, dependent,...). Since some Workers won't have payrolling-relevant partners, this attribute is not strictly required - we do advise to make sure this information is correct by the end of the payroll cycle though, as this will be taken into account for payrolling calculations.</b></li><br>
                <li><b><i>contractEndDate</i></b>, which should only be provided if the Worker is on a 'Fixed term'- or 'Well-defined work / Project-based'-contract.</li><br>
                <li><b><i>apprenticeContractNumber</i></b>, which should only be provided if the Worker is on a 'white- or blue-collar apprenticeship'-contract.</li><br>
                <li><b><i>nationalRegistrationNumber</i></b> is only required for Workers with Nationality "BEL".</li><br>
                <li><b><i>countryOfBirth</i></b> is only required for Workers with a Nationality other than "BEL".</li><br>
              </ul>
              </li><br>
          </ul>
          </li>
          <li><b>Supervisory Organization</b> can be provided with the ID that is known in your own HRIS, but will be mapped to an internal (department) identifier known to Partena.</li>
          <ul>
            <li>⚠️ Make sure to only use Supervisory Organization IDs that are already known by Partena. Get in touch with your contact person in case you're unsure. ⚠️</li>
          </ul><br>
          <li><b>Location</b> can be provided with the ID that is known in your own HRIS, but will be mapped to an internal (establishment) identifier known to Partena.</li>
          <ul>
            <li>⚠️ Make sure to only use Location IDs that are already known by Partena. Get in touch with your contact person in case you're unsure. ⚠️</li>
          </ul><br>
          <li><b>Pay Group</b> can be provided with the ID that is known in your own HRIS, but will be mapped to an internal (pay group) identifier known to Partena.</li>
          <ul>
            <li>⚠️ Make sure to only use Pay Group IDs that are already known by Partena. Get in touch with your contact person in case you're unsure. ⚠️</li>
          </ul><br>
          <li><b>Model contract:</b> The <i>Model Contract</i> refers to the ExpertSalary Contract Template that is to be assigned to this <i>Worker</i>. This template already defines a good handful of contract details such as <i>professional category</i> and <i>NACE code</i> which are specific to Belgian law and are not expected to be maintained in your HRIS. This <i>Model Contract</i> should first be created through ExpertSalary's GUI before it can be used to register a new Hire.</li><br>
          <li><b>Position Title:</b> This is the Title that will be printed on the Worker's payslip. While it is technically a freeform-field, it is advised to maintain a certain level of consistency in naming. For each <i>tenant</i>, Partena maintains a list with the used Position Titles and we would like to avoid multiple entries for semantically identical Titles.</li><br>
          <li><b>Response.workerId:</b> In the response body, the <i>workerId</i>-attribute represents the unique identifier that is used to register the Worker at Partena. For each future <i>'Worker data change'</i>, this identifier should be provided in the API request as a path parameter. For this reason, it is strongly advised to also capture this identifier in your own HRIS and link it to the Worker.
          <ul>
            <li>⚠️ In certain <i>'Worker data change'</i>-scenarios, this identifier can be subject to change and should be historized in your system. It is suggested to maintain a history of previously assigned Worker IDs (including dates) and be able to identify the currently active one. ⚠️</li>
          </ul>
          </li><br>
          <li><b>Dates</b> are to be provided in format  <b>YYYY-MM-DD</b></li><br>
        </ul>
      requestBody:
        $ref: '#/components/requestBodies/WorkerCreate'
      responses:
        '201':
          $ref: '#/components/responses/Created'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /wd-es/v1/worker/{worker_id}:
    put:
      summary: Update worker (delta)
      tags: [Worker data change]
      description: |
        Upon making changes to any of the Worker-attributes in scope for this integration (refer to request Schema), this interface should be used to propagate that same change to Partena's system of records.<br><br>
        <u><b>Baseline principles:</b></u><br>
        <ul>
          <li><b>Required request body attributes:</b> None of the body attributes are strictly required, a delta of the changes will suffice to update the Worker data. However, some attributes need to be provided in 'group', meaning that if one is provided, the other is required:<br><br>
          <ul>
            <li><b><i>relatedPersons-array:</i></b> upon making changes to an attribute in a Worker's <i>relatedPersons</i>-data, the <b>full set</b> of </i>relatedPersons</i>-data should be provided anew. This enables us to accurately perform recalculations of dependents data, which can have an impact on tax.</li><br>
            <li><b><i>totalBasePay:</i></b> upon making changes to a Worker's <i>totalBasePay</i>, a <i>compensationReason</i> and <i>effectiveDate</i> should be provided to justify the change in salary.</li><br>
            <li><b><i>address:</i></b> upon making changes to a Worker's <i>address</i>-object, the <i>effectiveDate</i> should be provided to indicate validity of this new address.</li><br>
            <li><b><i>maritalStatus:</i></b> upon making changes to a Worker's <i>maritalStatus</i>, the <i>maritalStatusEffectiveDate</i> should be provided to indicate validity of this new status.</li><br>
            <li><b><i>modelContract:</i></b> upon making providing a new <i>modelContract</i> (=assigning new contract & period), the <i>contractStartDate</i> for this period, as well as the <i>previousPeriodEndDate</i>, should be provided.<br><br>
              <ul>
                <li>If the Contract is of duration type 'Fixed term' or 'Well-defined work / Project-based', <i>contractEndDate</i> should also already be defined.</li><br>
                <li>Changing the contract could cause the Worker to be assigned a new ID.</li>
              </ul>
            </li><br>
          </ul>
          </li><br>
          <li><b>Limitations:</b><br><br>
            <ul>
              <li><b>Contracts and Contract Periods:</b><br><br>
              <ul>
                <li>For safety reasons, we do <b>not</b> offer the option to <b>delete</b> contracts (and contract periods) through this interface, this will need to be done manually, directly in Partena's software.</li><br>
                <li>Only the <i>current</i> contract period can be modified. When the <i>modelContract</i>-value remains stable but a new <i>contractStartDate</i> and/ or <i>contractEndDate</i> is provided, this will modify the <i>current</i> period.</li><br>
                <li>The <i>contractStartDate</i> shall always need to come <b>before</b> <i>contractEndDate</i>, but <b>after</b> the <i>previousPeriodEndDate</i></li>
              </ul>
            </ul>
          </li><br><br>
          <li><b>Dates</b> are to be provided in format <b>YYYY-MM-DD</b></li>
        </ul>
      parameters:
        - name: worker_id
          description: Identification of the Worker in Partena's system of records. Returned as <i>'workerId'</i> in successful New Hire response.
          in: path
          required: true
          schema: { type: string }
      requestBody:
        $ref: '#/components/requestBodies/WorkerChangeById'
      responses:
        '200':
          $ref: '#/components/responses/Updated'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /wd-es/v1/worker/{worker_id}/terminate:
    post:
      summary: Terminate worker
      description: |
        Upon <b>terminating</b> a Worker's contract <b>without immediately assigning a new one</b>, this interface should be used to propagate this state to Partena's system of records and stop payrolling for this Worker. Each request body attribute is required to succesfully submit the <b>Termination</b>.
      tags: [Termination]
      parameters:
        - name: worker_id
          description: Identification of the Worker in Partena's system of records. Returned as <i>'workerId'</i> in successful New Hire response.
          in: path
          required: true
          schema: { type: string }
      requestBody:
        $ref: '#/components/requestBodies/WorkerTerminate'
      responses:
        '200':
          $ref: '#/components/responses/WorkerTerminated'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  # =======================
  # Request Bodies
  # =======================
  requestBodies:
    WorkerCreate:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Worker_NewHire_Request'
          examples:
            New Hire (minimal):
              $ref: '#/components/examples/MinimalNewHire'
            New Hire:
              $ref: '#/components/examples/NewHire'
            New Hire (without Related Persons):
              $ref: '#/components/examples/NewHireNoRelated'
            New Hire (apprentice):
              $ref: '#/components/examples/NewHireApprentice'
            New Hire (fixed term):
              $ref: '#/components/examples/NewHireFixedTerm'
    WorkerChangeById:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Worker_Change_Request'
          examples:
            Update Address:
              $ref: '#/components/examples/UpdateAddress'
            Update Salary:
              $ref: '#/components/examples/UpdateSalary'
            Update Bank Account:
              $ref: '#/components/examples/UpdateBank'
            Change Model Contract:
              $ref: '#/components/examples/ChangeModelContract'
    WorkerTerminate:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Worker_Terminate_Request'
          examples:
            Terminate Melissa:
              $ref: '#/components/examples/TerminateWorker'

  # =======================
  # Responses
  # =======================
  responses:

    Created:
      description: The Worker was successfully registered with Partena.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Worker_NewHire_Success_Response'

    Updated:
      description: The Worker was updated successfully. If a new Partena Worker Id was assigned, it will be returned in <i>workerId</i>.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Worker_Change_Success_Response'

    WorkerTerminated:
      description: The Worker was terminated successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Worker_Terminate_Success_Response'

    Unauthorized:
      description: The provided <i>Bearer Token</i> was not valid or did not match the <i>tenant</i> provided in the request.
  
    NotFound:
      description: No Worker was found for the provided <i>workerId</i>.

    BadRequest:
      description: There was something wrong with your request. An error description guiding the remediation will be provided in <i>errorReason</i>. Correct your inputs and try again.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequest_Response'
    
    InternalServerError:
      description: Something went wrong internally. Please try again at a later time, or contact Partena if the issue persists for more than 24 hours.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Worker_NewHire_InternalServerError_Response'

  # =======================
  # Schemas
  # =======================
  schemas:

  #Request schemas
    Worker_NewHire_Request:
      type: object
      required: [companyReferenceId, personal, status, position]
      properties:
        id:
          type: string
          nullable: true
        supervisoryOrganization:
          type: string
          nullable: true
        companyReferenceId:
          type: string
        personal:
          type: object
          required: [person]
          properties:
            person:
              type: object
              required: [name, demographic, biographic]
              properties:
                name:
                  type: object
                  required: [lastName, firstName]
                  properties:
                    lastName: { type: string }
                    firstName: { type: string }
                governmentIDs:
                  type: array
                  nullable: true
                  items:
                    type: object
                    required: [type, id]
                    properties:
                      type: { type: string }
                      id: { type: string }
                demographic:
                  type: object
                  required: [nationality]
                  properties:
                    nationality: { type: string }
                    maritalStatus: { type: string, nullable: true }
                    maritalStatusEffectiveDate: { type: string, format: date, nullable: true}
                biographic:
                  type: object
                  required: [dateOfBirth]
                  properties:
                    gender: { type: string, nullable: true}
                    dateOfBirth: { type: string, format: date}
                    cityOfBirth: { type: string, nullable: true}
                    countryOfBirth: { type: string, nullable: true}
                    disabled: { type: boolean, nullable: true}
                contact: 
                  type: object
                  nullable: true
                  required:
                    - address
                  properties:
                    preferredCommunicationLanguage: { type: string, nullable: true}
                    address:
                      type: object
                      required: [street, houseNumber, country, municipality, postalCode]
                      properties:
                        street: { type: string }
                        houseNumber: { type: string }
                        box: { type: string, nullable: true}
                        country: { type: string }
                        municipality: { type: string }
                        postalCode: { type: string }
                qualification:
                  type: object
                  nullable: true
                  properties:
                    education:
                      type: object
                      nullable: true
                      properties:
                        degree: { type: string, nullable: true}
                relatedPersons:
                  type: array
                  nullable: true
                  items:
                    type: object
                    required: [name, biographic, dependent, relationshipType]
                    properties:
                      relationshipType:
                        type: string
                      name:
                        type: object
                        required: [lastName, firstName]
                        properties:
                          lastName: { type: string }
                          firstName: { type: string }
                      biographic:
                        type: object
                        required: [dateOfBirth]
                        properties:
                          dateOfBirth: { type: string, format: date}
                      dependent:
                        type: object
                        required: [disabled, fullTimeStudent]
                        properties:
                          disabled: { type: boolean }
                          fullTimeStudent: { type: boolean }
        status:
          type: object
          required: [contractStartDate]
          properties:
            dateEnteredWorkforce: { type: string, format: date, nullable: true}
            continuousServiceDate: { type: string, format: date, nullable: true}
            contractStartDate: { type: string, format: date}
            contractEndDate: { type: string, format: date, nullable: true}
        compensation:
          type: object
          nullable: true
          required: [frequency, totalBasePay]
          properties:
            effectiveDate: { type: string, format: date, nullable: true}
            frequency: { type: string }
            totalBasePay: { type: number }
            bankAccountDetails:
              type: object
              properties:
                iban: { type: string, nullable: true}
                bic: { type: string, nullable: true}
                accountHolderName: { type: string, nullable: true}
        position:
          type: object
          required: [modelContract]
          properties:
            modelContract: { type: string }
            positionTitle: { type: string, nullable: true}
            apprenticeContractNumber: { type: string, nullable: true}
            organization:
              type: object
              nullable: true
              required: [payGroup, location]
              properties:
                payGroup:
                  type: string
                location:
                  type: string


    # change payload (PUT)
    Worker_Change_Request:
      type: object
      required: [companyReferenceId]
      properties:
        id:
          type: string
          nullable: true
        supervisoryOrganization:
          type: string
          nullable: true
        companyReferenceId:
          type: string
        personal:
          type: object
          nullable: true
          properties:
            person:
              type: object
              nullable: true
              properties:
                name:
                  type: object
                  nullable: true
                  properties:
                    lastName: { type: string, nullable: true}
                    firstName: { type: string, nullable: true}
                governmentIDs:
                  type: array
                  nullable: true  
                  items:
                    type: object
                    properties:
                      type: { type: string, nullable: true}
                      id: { type: string, nullable: true}
                demographic:
                  type: object
                  nullable: true
                  properties:
                    nationality: { type: string, nullable: true}
                    maritalStatus: { type: string, nullable: true}
                    maritalStatusEffectiveDate: { type: string, format: date, nullable: true}
                biographic:
                  type: object
                  nullable: true
                  properties:
                    gender: { type: string, nullable: true}
                    dateOfBirth: { type: string, format: date, nullable: true}
                    cityOfBirth: { type: string, nullable: true}
                    countryOfBirth: { type: string, nullable: true}
                    disabled: { type: boolean, nullable: true}
                contact:
                  type: object
                  nullable: true
                  properties:
                    preferredCommunicationLanguage: { type: string, nullable: true}
                    address:
                      type: object
                      nullable: true
                      properties:
                        effectiveDate: { type: string, format: date, nullable: true}
                        street: { type: string, nullable: true}
                        houseNumber: { type: string, nullable: true}
                        box: { type: string, nullable: true}
                        country: { type: string, nullable: true}
                        municipality: { type: string, nullable: true}
                        postalCode: { type: string, nullable: true}
                qualification:
                  type: object
                  nullable: true
                  properties:
                    education:
                      type: object
                      nullable: true
                      properties:
                        degree: { type: string, nullable: true}
                relatedPersons:
                  type: array
                  nullable: true
                  items:
                    type: object
                    required: [relationshipType, name, biographic, dependent]
                    properties:
                      relationshipType:
                        type: string
                      name:
                        type: object
                        required: [firstName, lastName]
                        properties:
                          lastName: { type: string }
                          firstName: { type: string }
                      biographic:
                        type: object
                        required: [dateOfBirth]
                        properties:
                          dateOfBirth: { type: string, format: date}
                      dependent:
                        type: object
                        required: [disabled, fullTimeStudent]
                        properties:
                          disabled: { type: boolean }
                          fullTimeStudent: { type: boolean }
        status:
          type: object
          nullable: true
          properties:
            dateEnteredWorkforce: { type: string, format: date, nullable: true}
            continuousServiceDate: { type: string, format: date, nullable: true}
            contractStartDate: { type: string, format: date, nullable: true}
            contractEndDate: { type: string, format: date, nullable: true}
            previousPeriodEndDate: { type: string, format: date, nullable: true}
        compensation:
          type: object
          nullable: true
          properties:
            effectiveDate: { type: string, format: date, nullable: true}
            frequency: { type: string, nullable: true}
            totalBasePay: { type: number, nullable: true}
            bankAccountDetails:
              type: object
              nullable: true
              properties:
                iban: { type: string, nullable: true}
                bic: { type: string, nullable: true}
                accountHolderName: { type: string, nullable: true}
            compensationReason: { type: string, nullable: true}
        position:
          type: object
          nullable: true
          properties:
            modelContract: { type: string, nullable: true}
            positionTitle: { type: string, nullable: true}
            apprenticeContractNumber: { type: string, nullable: true}
            organization:
              type: object
              nullable: true
              properties:
                payGroup:
                  type: string
                  nullable: true
                location:
                  type: string
                  nullable: true

    # termination payload (POST /terminate)
    Worker_Terminate_Request:
      type: object
      required: [companyReferenceId, status]
      properties:
        companyReferenceId:
          type: string
        status:
          type: object
          required: [terminationStatus]
          properties:
            terminationStatus:
              type: object
              required: [localTerminationReason, notificationDate, terminationDate]
              properties:
                localTerminationReason:
                  type: string
                  description: "Reason for contract termination"
                notificationDate:
                  type: string
                  format: date
                  description: "Date on which the termination was communication (yyyy-mm-dd)"
                terminationDate:
                  type: string
                  format: date
                  description: "Termination date (yyyy-mm-dd)"

  #Response schemas
    Worker_NewHire_Success_Response:
      type: object
      properties:
        result:
          type: string
          enum:
            - success
        workerId:
          type: string

    Worker_Change_Success_Response:
      type: object
      properties:
        result:
          type: string
          enum:
            - success
        workerId:
          type: string

    Worker_Terminate_Success_Response:
      type: object
      properties:
        result:
          type: string
          enum:
            - success
          
    BadRequest_Response:
      type: object
      properties:
        result:
          type: string
          enum:
            - bad request
        errorReason:
          type: string
      example:
        result: "bad request"
        errorReason: "BGHL is not a valid Nationality"

    Worker_NewHire_InternalServerError_Response:
      type: object
      properties:
        result:
          type: string
          enum:
            - internal server error
        errorReason:
          type: string
          enum:
            - Something went wrong. Please try again at a later time.


  # =======================
  # Examples
  # =======================
  examples:

    MinimalNewHire:
      summary: New Hire with minimal attributes for registration (not payroll-ready)
      value:
        companyReferenceId: "8210"
        personal:
          person:
            governmentIDs: 
              - type: "National Registration Number"
                id: "000000-000-00"
            name:
              lastName: "Doe"
              firstName: "John"
            demographic:
              nationality: "BEL"
            biographic:
              dateOfBirth: "1990-01-01"
        status:
          contractStartDate: "2025-01-01"
        position:
          modelContract: "CUSTOM_001"

    NewHire:
      summary: New Hire (payroll-ready)
      value:
        id: "BEL_00001"
        supervisoryOrganization: "CC_123"
        companyReferenceId: "8210"
        personal:
          person:
            name:
              lastName: "Doe"
              firstName: "John"
            governmentIDs: 
              - type: "National Registration Number"
                id: "000000-000-00"
            demographic:
              nationality: "BEL"
              maritalStatus: "Married"
              maritalStatusEffectiveDate: "2018-01-09"
            biographic:
              gender: "Male"
              dateOfBirth: "1990-01-01"
              cityOfBirth: "Brussels"
              countryOfBirth: "Belgium"
              disabled: false
            contact:
              preferredCommunicationLanguage: "Dutch"
              address:
                street: "Main Street"
                houseNumber: "1"
                box: "PO Box 1"
                country: "Belgium"
                municipality: "Brussels"
                postalCode: "1000"
            qualification:
              education:
                degree: "BA"
            relatedPersons:
              - relationshipType: "Spouse"
                name:
                  lastName: "Doe"
                  firstName: "Jane"
                biographic:
                  dateOfBirth: "1992-12-05"
                dependent:
                  disabled: false
                  fullTimeStudent: false
        status:
          dateEnteredWorkforce: "2020-08-01"
          continuousServiceDate: "2020-08-01"
          contractStartDate: "2020-08-01"
          contractEndDate: "2026-08-01"
        compensation:
          effectiveDate: "2023-10-01"
          frequency: "Monthly"
          totalBasePay: 3000.25
          bankAccountDetails:
            iban: "BE00000000000000"
            bic: "TESTBEBB"
            accountHolderName: "JOHN DOE"
        position:
          modelContract: "CUSTOM_001"
          positionTitle: "Software Developer"
          organization:
            payGroup: "OT_123"
            location: "LOC_123"

    NewHireNoRelated:
      summary: New Hire (without Related Persons)
      value:
        id: "BEL_00001"
        supervisoryOrganization: "CC_123"
        companyReferenceId: "8210"
        personal:
          person:
            name:
              lastName: "Doe"
              firstName: "John"
            governmentIDs:
              - type: "National Registration Number"
                id: "000000-000-00"
            demographic:
              nationality: "BEL"
              maritalStatus: "1"
              maritalStatusEffectiveDate: "2018-01-09"
            biographic:
              gender: "Male"
              dateOfBirth: "1990-01-01"
              cityOfBirth: "Brussels"
              countryOfBirth: "Belgium"
              disabled: false
            contact:
              preferredCommunicationLanguage: "Dutch"
              address:
                street: "Main Street"
                houseNumber: "1"
                country: "Belgium"
                municipality: "Brussels"
                postalCode: "1000"
            qualification:
              education:
                degree: "BA"
        status:
          dateEnteredWorkforce: "2016-08-01"
          continuousServiceDate: "2018-08-31"
          contractStartDate: "2020-08-01"
        compensation:
          effectiveDate: "2023-10-01"
          frequency: "Monthly"
          totalBasePay: 3000.25
          bankAccountDetails:
            iban: "BE00000000000000"
            bic: "TESTBEBB"
            accountHolderName: "JOHN DOE"
        position:
          modelContract: "CUSTOM_001"
          positionTitle: "Software Developer"
          organization:
            payGroup: "OT_123"
            location: "LOC_123"

    NewHireApprentice:
      summary: New Hire (Apprentice)
      value:
        id: "BEL_00001"
        supervisoryOrganization: "CC_123"
        companyReferenceId: "8210"
        personal:
          person:
            name:
              lastName: "Doe"
              firstName: "John"
            governmentIDs:
              - type: "National Registration Number"
                id: "000000-000-00"
            demographic:
              nationality: "BEL"
              maritalStatus: "1"
              maritalStatusEffectiveDate: "2018-01-09"
            biographic:
              gender: "Male"
              dateOfBirth: "1990-01-01"
              cityOfBirth: "Brussels"
              countryOfBirth: "Belgium"
              disabled: false
            contact:
              preferredCommunicationLanguage: "Dutch"
              address:
                street: "Main Street"
                houseNumber: "1"
                country: "Belgium"
                municipality: "Brussels"
                postalCode: "1000"
            qualification:
              education:
                degree: "BA"
        status:
          dateEnteredWorkforce: "2016-08-01"
          continuousServiceDate: "2018-08-31"
          contractStartDate: "2020-08-01"
        compensation:
          effectiveDate: "2023-10-01"
          frequency: "Monthly"
          totalBasePay: 3000.25
          bankAccountDetails:
            iban: "BE00000000000000"
            bic: "TESTBEBB"
            accountHolderName: "JOHN DOE"
        position:
          modelContract: "CUSTOM_001_APPR"
          positionTitle: "Apprentice Software Developer"
          apprenticeContractNumber: "123456789-1234"
          organization:
            payGroup: "OT_123"
            location: "LOC_123"

    NewHireFixedTerm:
      summary: New Hire (Fixed Term)
      value:
        id: "BEL_00001"
        supervisoryOrganization: "CC_123"
        companyReferenceId: "8210"
        personal:
          person:
            name:
              lastName: "Doe"
              firstName: "John"
            governmentIDs:
              - type: "National Registration Number"
                id: "000000-000-00"
            demographic:
              nationality: "BEL"
              maritalStatus: "1"
              maritalStatusEffectiveDate: "2018-01-09"
            biographic:
              gender: "Male"
              dateOfBirth: "1990-01-01"
              cityOfBirth: "Brussels"
              countryOfBirth: "Belgium"
              disabled: false
            contact:
              preferredCommunicationLanguage: "Dutch"
              address:
                street: "Main Street"
                houseNumber: "1"
                country: "Belgium"
                municipality: "Brussels"
                postalCode: "1000"
            qualification:
              education:
                degree: "BA"
        status:
          dateEnteredWorkforce: "2016-08-01"
          continuousServiceDate: "2018-08-31"
          contractStartDate: "2025-08-01"
          contractEndDate: "2026-08-01"
        compensation:
          effectiveDate: "2023-10-01"
          frequency: "Monthly"
          totalBasePay: 3000.25
          bankAccountDetails:
            iban: "BE00000000000000"
            bic: "TESTBEBB"
            accountHolderName: "JOHN DOE"
        position:
          modelContract: "CUSTOM_001"
          positionTitle: "Software Developer"
          organization:
            payGroup: "OT_123"
            location: "LOC_123"

    UpdateAddress:
      summary: Address change
      value:
        companyReferenceId: "8210"
        personal:
          person:
            contact:
              address:
                effectiveDate: "2024-08-01"
                street: "New Street"
                houseNumber: "101"
                box: "B12"
                country: "Belgium"
                municipality: "Antwerp"
                postalCode: "2000"

    ChangeModelContract:
      summary: Change Model Contract
      value:
        companyReferenceId: "8210"
        status:
          contractStartDate: "2025-09-08"
          previousPeriodEndDate: "2025-09-05"
        position:
          modelContract: "CUSTOM_003"
          positionTitle: "Software Consultant"

    UpdateSalary:
      summary: Salary raise
      value:
        companyReferenceId: "8210"
        compensation:
          totalBasePay: 3500.00
          compensationReason: "Annual indexation"
          effectiveDate: "2025-01-01"

    UpdateBank:
      summary: Bank account details change
      value:
        companyReferenceId: "8210"
        compensation:
          bankAccountDetails:
            iban: "BE11111111111111"
            bic: "NEWBEBB"
            accountHolderName: "JOHN DOE"

    TerminateWorker:
      summary: Termination
      value:
        companyReferenceId: "8210"
        status:
          terminationStatus:
            localTerminationReason: "End of fixed-term contract"
            notificationDate: "2025-05-15"
            terminationDate: "2025-06-30"

